title: Gnr8tr systems status page
baseURL: https://status.gnr8tr.online/
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Website
      description: Our company public facing website
      link: http://www.gnr8tr.online/
    - name: Helpdesk
      description: Our company customer support and feedback site
      link: https://blog.gnr8tr.online/
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " IST"
  logo: /images/clearstatus.svg
  description_header: Information about <a class='text-grey-darkest' title='Visit
    gnr8tr.online' href='http://www.gnr8tr.online/'>Gnr8tr</a> systems
    operations.<br />Follow us <a class='text-grey-darkest' title='Visit our
    page on Twitter' href='https://twitter.com/freceipt_gnr8tr'>on Twitter</a>
    or subscribe to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be
    alerted of new events.
  copyrightHolder: Gnr8tr Online Tech.
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit gnr8tr.online'
    href='http://www.gnr8tr.online/'>gnr8tr.online</a> allows you to
    create/generate/gnr8/make rent, fuel, petrol, diesel, driver salary
    receipts/bills/invoices for india.
